### ISSUE TITLE
Change of Project Title from Cproject to College Project

### ISSUE THREAD

**Issue by gutsytechster** [GeekyFreelancers/Cproject#6]
The current project title Cproject seems bit confusing and ambiguous. It looks like the project is somewhat related to the "C" language. So, I think for more comprehensiveness, title should be changed.
Do give your reviews regarding this.

**Comment by InquiridorTechie** [comment]
Prashant I think it is already mentioned in the Readme file that C is for College.
If we change the project name at this time then we also need to change it in settings.py and manage.py files or may be some other location. We should have consider this issue at the initial stage. I think the current title is ok.
Rest is up to the shubham as he is the administrator.

**Comment by gutsytechster** [comment]
Neeraj, I get your concerns. Though I am just asking to change the project name. The main file which Django uses is the inner file which initially has the same name as project name. But the project name can be changed, it doesn't affect the files and folders inside it. I just don't want to get anyone mislead from the name. Some people just doesn't see the README file at first.
However, if all agree to it. That'll be ok.

**Comment by cypher-naman** [comment]
yeah, it seems misleading as another developer I would assume it to be a project based on C language rather than college. So, I would support changing the name to college project.
If the changes are too irreversible to make then we have to bear this name.

**Comment by VirtualRcoder** [comment]
We will also have to delete this project from here and recreate it here (on github), which will be a waste of time. So after completing this project we will change it's name. As only we have to work on it.

**Comment by cypher-naman** [comment]
just close this issue VirtualRcoder

**Comment by VirtualRcoder** [comment]
Ok Cypher
